### ISSUE TITLE
Crash with Fabric Networking API v1

### ISSUE THREAD

**Issue by K0-RR** [Juuxel/VanillaParts#21]
---- Minecraft Crash Report ----
// Don't do that.

Time: 2020-12-10 23:43:09 CET
Description: Exception ticking world

java.lang.ClassCastException: net.minecraft.class_3244 cannot be cast to net.fabricmc.fabric.api.network.PacketContext
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.1)
    at alexiil.mc.lib.net.impl.CoreMinecraftNetUtil.getConnection(CoreMinecraftNetUtil.java:96)
    at alexiil.mc.lib.multipart.impl.MultipartBlockEntity.sendInitialData(MultipartBlockEntity.java:86)
    at net.minecraft.server.world.ChunkHolder.handler$cad000$sendCustomUpdatePacket(ChunkHolder:550)
    at net.minecraft.server.world.ChunkHolder.sendBlockEntityUpdatePacket(ChunkHolder:254)
    at net.minecraft.server.world.ChunkHolder.tryUpdateBlockEntityAt(ChunkHolder:249)
    at net.minecraft.server.world.ChunkHolder.flushUpdates(ChunkHolder:234)
    at net.minecraft.server.world.ServerChunkManager.method_20801(ServerChunkManager:374)
    at java.util.ArrayList.forEach(ArrayList.java:1259)
    at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager:368)
    at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager:337)
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld:353)
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
    at net.minecraft.server.MinecraftServer.handler$cbl000$modifiedRunLoop(MinecraftServer:6310)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:651)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
    at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  All players: 1 total; [class_3222['_K0RR_'/145, l='ServerLevel[ustyfddsf]', x=77.06, y=63.00, z=37.38]]
  Chunk stats: ServerChunkCache: 2068
  Level dimension: minecraft:overworld
  Level spawn location: World: (48,64,0), Chunk: (at 0,4,0 in 3,0; contains blocks 48,0,0 to 63,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 14533 game time, 1916 day time
  Level name: ustyfddsf
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
  Level weather: Rain time: 133052 (now: false), thunder time: 124246 (now: false)
  Known server brands: fabric
  Level was modded: true
  Level storage version: 0x04ABD - Anvil

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Linux (amd64) version 5.4.70-amd64-desktop
  Java Version: 1.8.0_275, BellSoft
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), BellSoft
  Memory: 4213728280 bytes (4018 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
  CPUs: 8
  JVM Flags: 8 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=51 -XX:G1HeapRegionSize=32M -Xms8192m -Xmx8192m
  Suspected Mods: LibMultiPart (libmultipart), Lib Network Stack (libnetworkstack)

**Comment by K0-RR** [comment]
I removed other mods (yes, Sodium too), so this is another crash report.

**Comment by K0-RR** [comment]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 12/11/20 2:15 AM
Description: Exception ticking world

java.lang.ClassCastException: net.minecraft.class_3244 cannot be cast to net.fabricmc.fabric.api.network.PacketContext
	at alexiil.mc.lib.net.impl.CoreMinecraftNetUtil.getConnection(CoreMinecraftNetUtil.java:96)
	at alexiil.mc.lib.multipart.impl.MultipartBlockEntity.sendInitialData(MultipartBlockEntity.java:86)
	at net.minecraft.class_3193.handler$zfj000$sendCustomUpdatePacket(class_3193.java:550)
	at net.minecraft.class_3193.method_14009(class_3193.java:254)
	at net.minecraft.class_3193.method_30311(class_3193.java:249)
	at net.minecraft.class_3193.method_14006(class_3193.java:234)
	at net.minecraft.class_3215.method_20801(class_3215.java:374)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at net.minecraft.class_3215.method_14161(class_3215.java:368)
	at net.minecraft.class_3215.method_12127(class_3215.java:337)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at alexiil.mc.lib.net.impl.CoreMinecraftNetUtil.getConnection(CoreMinecraftNetUtil.java:96)
	at alexiil.mc.lib.multipart.impl.MultipartBlockEntity.sendInitialData(MultipartBlockEntity.java:86)
	at net.minecraft.class_3193.handler$zfj000$sendCustomUpdatePacket(class_3193.java:550)
	at net.minecraft.class_3193.method_14009(class_3193.java:254)
	at net.minecraft.class_3193.method_30311(class_3193.java:249)
	at net.minecraft.class_3193.method_14006(class_3193.java:234)
	at net.minecraft.class_3215.method_20801(class_3215.java:374)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at net.minecraft.class_3215.method_14161(class_3215.java:368)
	at net.minecraft.class_3215.method_12127(class_3215.java:337)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Affected level --
Details:
	All players: 1 total; [class_3222['_K0RR_'/8, l='ServerLevel[flat shit]', x=199.10, y=4.00, z=-23.27]]
	Chunk stats: ServerChunkCache: 3211
	Level dimension: minecraft:overworld
	Level spawn location: World: (208,4,-32), Chunk: (at 0,0,0 in 13,-2; contains blocks 208,0,-32 to 223,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 231 game time, 231 day time
	Level name: flat shit
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 69198 (now: false), thunder time: 145604 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 5.4.70-amd64-desktop
	Java Version: 1.8.0_275, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), BellSoft
	Memory: 6469776216 bytes (6170 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 8 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=51 -XX:G1HeapRegionSize=32M -Xms8192m -Xmx8192m
	Fabric Mods: 
		fabric: Fabric API 0.28.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.0+a03e98793a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.2+a03e98793a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		libblockattributes_core: LibBlockAttributes (Core) 0.8.4
		libmultipart: LibMultiPart 0.4.3
		libmultipart_deps_container: LibMultiPart (Dependency Container) 0.4.3
		libnetworkstack: Lib Network Stack 0.4.1
		minecraft: Minecraft 1.16.4
		modmenu: Mod Menu 1.14.13+build.19
		vanilla_parts: Vanilla Parts 1.1.4+1.16.3
	Player Count: 1 / 8; [class_3222['_K0RR_'/8, l='ServerLevel[flat shit]', x=199.10, y=4.00, z=-23.27]]
	Data Packs: vanilla, fabric/fabric-tool-attribute-api-v1
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by Juuxel** [comment]
LibMultipart seems to be incompatible with the new Fabric API version, try downgrading to 0.27.

**Comment by AlexIIL** [comment]
Sorry about that, I'll push an update to LibNetworkStack soon.

**Comment by AlexIIL** [comment]
I've released a fixed version of LibNetworkStack: [0.4.3](https://alexiil.uk/maven/alexiil/mc/lib/libnetworkstack-base/0.4.3/libnetworkstack-base-0.4.3.jar).

**Comment by AlexIIL** [comment]
Sorry for the (long) delay - LMP [0.4.6](https://alexiil.uk/maven/alexiil/mc/lib/libmultipart-all/0.4.6/libmultipart-all-0.4.6.jar) now has an updated version of LibNetworkStack, which should fix this.
